import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:permission_handler/permission_handler.dart';

import '../../../../app/theme.dart';
import '../../../../core/utils/app_logger.dart';
import '../../../../shared/providers/app_providers.dart';
import '../../domain/entities/drive_folder.dart';
import '../../domain/entities/sync_task.dart';
import 'drive_folder_picker_screen.dart';

/// Add New Sync Task screen (FR-3).
///
/// Form with remote folder picker, local folder picker,
/// sync frequency selector, and two-way sync toggle.
/// Creates a task via the SyncTask repository on save.
class AddTaskScreen extends ConsumerStatefulWidget {
  const AddTaskScreen({super.key});

  @override
  ConsumerState<AddTaskScreen> createState() => _AddTaskScreenState();
}

class _AddTaskScreenState extends ConsumerState<AddTaskScreen> {
  final _nameController = TextEditingController();
  DriveFolder? _selectedRemoteFolder;
  String? _localFolderPath;
  SyncFrequency _syncFrequency = SyncFrequency.onChange;
  bool _isTwoWaySync = false;
  bool _isSaving = false;

  @override
  void dispose() {
    _nameController.dispose();
    super.dispose();
  }

  bool get _isFormValid =>
      _nameController.text.trim().isNotEmpty &&
      _selectedRemoteFolder != null &&
      _localFolderPath != null;

  Future<void> _saveTask() async {
    if (!_isFormValid || _isSaving) return;

    setState(() => _isSaving = true);

    try {
      final repo = ref.read(syncTaskRepositoryProvider);
      await repo.createTask(
        SyncTask(
          id: '', // will be generated by repository
          name: _nameController.text.trim(),
          remotePath: _selectedRemoteFolder!.id,
          remoteFolderName: _selectedRemoteFolder!.name,
          localPath: _localFolderPath!,
          syncFrequency: _syncFrequency,
          isTwoWaySync: _isTwoWaySync,
        ),
      );

      // Invalidate the tasks stream so dashboard refreshes
      ref.invalidate(syncTasksStreamProvider);

      if (mounted) context.pop();
    } catch (e) {
      setState(() => _isSaving = false);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to create task: $e'),
            backgroundColor: AppTheme.statusError,
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.backgroundLight,
      appBar: AppBar(
        backgroundColor: AppTheme.surfaceLight,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => context.pop(),
        ),
        title: const Text('Add New Sync Task'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(AppTheme.spacingMd),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // ── Task Name ──
            _SectionHeader(title: 'Task Name'),
            const SizedBox(height: AppTheme.spacingSm),
            TextField(
              controller: _nameController,
              decoration: const InputDecoration(
                hintText: 'e.g., Work Documents',
              ),
              onChanged: (_) => setState(() {}),
            ),
            const SizedBox(height: AppTheme.spacingLg),

            // ── Google Drive Folder ──
            _SectionHeader(title: 'Google Drive Folder'),
            const SizedBox(height: AppTheme.spacingSm),
            _FolderPicker(
              label: 'Select Remote Folder',
              selectedPath: _selectedRemoteFolder?.path,
              icon: Icons.cloud_outlined,
              onTap: () async {
                final selectedFolder = await Navigator.of(context)
                    .push<DriveFolder>(
                      MaterialPageRoute(
                        builder: (context) => const DriveFolderPickerScreen(),
                      ),
                    );
                if (selectedFolder != null) {
                  setState(() => _selectedRemoteFolder = selectedFolder);
                }
              },
            ),
            const SizedBox(height: AppTheme.spacingLg),

            // ── Local Android Folder ──
            _SectionHeader(title: 'Local Android Folder'),
            const SizedBox(height: AppTheme.spacingSm),
            _FolderPicker(
              label: 'Select Local Folder',
              selectedPath: _localFolderPath,
              icon: Icons.folder_outlined,
              onTap: () async {
                AppLogger.d(
                  '[AddTaskScreen] Launching native local folder picker',
                );
                try {
                  final manageStatus = await Permission.manageExternalStorage
                      .request();
                  final storageStatus = await Permission.storage.request();

                  if (!manageStatus.isGranted && !storageStatus.isGranted) {
                    AppLogger.w('[AddTaskScreen] Storage permissions denied');
                    if (context.mounted) {
                      ScaffoldMessenger.of(context).showSnackBar(
                        const SnackBar(
                          content: Text(
                            'Storage permission is required to read/write files.',
                          ),
                        ),
                      );
                    }
                  }

                  final result = await FilePicker.platform.getDirectoryPath(
                    dialogTitle: 'Select Local Folder',
                  );
                  if (result != null) {
                    AppLogger.i(
                      '[AddTaskScreen] User selected local folder: $result',
                    );
                    setState(() => _localFolderPath = result);
                  } else {
                    AppLogger.d(
                      '[AddTaskScreen] User cancelled native local folder picker',
                    );
                  }
                } catch (e, stack) {
                  AppLogger.e(
                    '[AddTaskScreen] Native local folder picker failed',
                    error: e,
                    stackTrace: stack,
                  );
                }
              },
            ),
            const SizedBox(height: AppTheme.spacingLg),

            // ── Sync Frequency ──
            _SectionHeader(title: 'Sync Frequency'),
            const SizedBox(height: AppTheme.spacingSm),
            ...SyncFrequency.values.map(
              (freq) => _FrequencyOption(
                title: freq.label,
                subtitle: switch (freq) {
                  SyncFrequency.onChange => 'Real-time synchronization',
                  SyncFrequency.hourly => 'Sync every 60 minutes',
                  SyncFrequency.daily => 'Once every 24 hours',
                },
                value: freq,
                groupValue: _syncFrequency,
                onChanged: (v) => setState(() => _syncFrequency = v),
              ),
            ),
            const SizedBox(height: AppTheme.spacingLg),

            // ── Two-Way Sync ──
            _SectionHeader(title: 'Two-Way Sync'),
            const SizedBox(height: AppTheme.spacingSm),
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: AppTheme.surfaceLight,
                borderRadius: BorderRadius.circular(AppTheme.radiusLg),
                border: Border.all(color: const Color(0xFFE2E8F0)),
              ),
              child: Row(
                children: [
                  Expanded(
                    child: Text(
                      'Keep changes on both Google Drive and your '
                      'Android device synchronized.',
                      style: Theme.of(context).textTheme.bodyMedium,
                    ),
                  ),
                  Switch(
                    value: _isTwoWaySync,
                    activeTrackColor: AppTheme.primary,
                    onChanged: (v) => setState(() => _isTwoWaySync = v),
                  ),
                ],
              ),
            ),
            const SizedBox(height: AppTheme.spacingXl),

            // ── Save Button ──
            SizedBox(
              width: double.infinity,
              child: ElevatedButton(
                onPressed: _isFormValid && !_isSaving ? _saveTask : null,
                child: _isSaving
                    ? const SizedBox(
                        width: 20,
                        height: 20,
                        child: CircularProgressIndicator(
                          strokeWidth: 2,
                          color: AppTheme.textOnPrimary,
                        ),
                      )
                    : const Text('Create Sync Task'),
              ),
            ),
            const SizedBox(height: AppTheme.spacingMd),
          ],
        ),
      ),
    );
  }
}

// ── Helper Widgets ──────────────────────────────────

class _SectionHeader extends StatelessWidget {
  const _SectionHeader({required this.title});
  final String title;

  @override
  Widget build(BuildContext context) {
    return Text(
      title,
      style: Theme.of(
        context,
      ).textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w700),
    );
  }
}

class _FolderPicker extends StatelessWidget {
  const _FolderPicker({
    required this.label,
    required this.icon,
    this.selectedPath,
    this.onTap,
  });

  final String label;
  final IconData icon;
  final String? selectedPath;
  final VoidCallback? onTap;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: AppTheme.surfaceLight,
          borderRadius: BorderRadius.circular(AppTheme.radiusLg),
          border: Border.all(color: const Color(0xFFE2E8F0)),
        ),
        child: Row(
          children: [
            Icon(icon, color: AppTheme.primary),
            const SizedBox(width: 12),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(label, style: Theme.of(context).textTheme.titleSmall),
                  if (selectedPath != null) ...[
                    const SizedBox(height: 2),
                    Text(
                      selectedPath!,
                      style: Theme.of(context).textTheme.bodySmall,
                    ),
                  ] else
                    Text(
                      'None selected',
                      style: Theme.of(context).textTheme.bodySmall?.copyWith(
                        color: AppTheme.textSecondary,
                      ),
                    ),
                ],
              ),
            ),
            const Icon(Icons.chevron_right, color: AppTheme.textSecondary),
          ],
        ),
      ),
    );
  }
}

class _FrequencyOption extends StatelessWidget {
  const _FrequencyOption({
    required this.title,
    required this.subtitle,
    required this.value,
    required this.groupValue,
    required this.onChanged,
  });

  final String title;
  final String subtitle;
  final SyncFrequency value;
  final SyncFrequency groupValue;
  final ValueChanged<SyncFrequency> onChanged;

  @override
  Widget build(BuildContext context) {
    final isSelected = value == groupValue;

    return GestureDetector(
      onTap: () => onChanged(value),
      child: Container(
        margin: const EdgeInsets.only(bottom: 8),
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: AppTheme.surfaceLight,
          borderRadius: BorderRadius.circular(AppTheme.radiusLg),
          border: Border.all(
            color: isSelected ? AppTheme.primary : const Color(0xFFE2E8F0),
            width: isSelected ? 2 : 1,
          ),
        ),
        child: Row(
          children: [
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    title,
                    style: Theme.of(context).textTheme.titleSmall?.copyWith(
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                  Text(subtitle, style: Theme.of(context).textTheme.bodySmall),
                ],
              ),
            ),
            Icon(
              isSelected
                  ? Icons.radio_button_checked
                  : Icons.radio_button_unchecked,
              color: isSelected ? AppTheme.primary : AppTheme.textSecondary,
            ),
          ],
        ),
      ),
    );
  }
}
